export const dataEvaluate = [
  {
    id: 1,
    imgE: 'https://quanlykho.vn/wp-content/uploads/2019/11/quay-ba-thuong-co-khach-san-lon.png',
    avt: 'https://kinhtechungkhoan.vn/stores/news_dataimages/thuydung/052022/20/11/4451_SharkBinh.jpg?rt=20220520114454',
    name: 'Shark Bình',
    date: '7/06/2022',
    premiumTwin: 'Premium Twin',
    time: '2 đêm. Tháng 6/2022',
    evaluate: 'Tuyệt vời, trải nghiệm tuyệt vời',
    coment: 'Bữa ăn sáng phong phú, phòng đẹp.Thiết kế phòng hiện đại, sáng tạo - Hệ thống nước mạnh dù mình ở tầng cao nhất - Có chiến dịch bảo vệ môi trường - Dọn phòng nhanh chóng - Wifi ổn định, tivi nhiều kênh và rõ nét - Có hầm đỗ xe tiện nghi - Có hồ bơi và quầy bar - Check out nhanh chóng - Toàn bộ nhân viên đều rất trẻ',
    point: '9.9',
    cmt: 'Tuyệt vời',
  },

  {
    id: 2,
    imgE: 'https://vcdn-dulich.vnecdn.net/2020/09/11/Khach-san-tim-huong-di-moi-3-2389-1599800270.jpg',
    avt: 'https://baohay.vn/wp-content/uploads/2019/08/nguyen-xuan-phu.jpg',
    name: 'Shark Phú',
    date: '11/05/2022',
    premiumTwin: 'Premium Twin',
    time: '2 đêm. Tháng 6/2022',
    evaluate: 'Cảnh đẹp, khách sạn sang trọng tiện nghi',
    coment: 'Bữa ăn sáng phong phú, phòng đẹp.Thiết kế phòng hiện đại, sáng tạo - Hệ thống nước mạnh dù mình ở tầng cao nhất - Có chiến dịch bảo vệ môi trường - Dọn phòng nhanh chóng - Wifi ổn định, tivi nhiều kênh và rõ nét - Có hầm đỗ xe tiện nghi - Có hồ bơi và quầy bar - Check out nhanh chóng - Toàn bộ nhân viên đều rất trẻ',
    point: '9.7',
    cmt: 'Tuyệt vời',
  },
  {
    id: 3,
    imgE: 'https://tuyensinhcaodangdulich.edu.vn/upload/con-gai-co-nen-hoc-nganh-quan-tri-khach-san-nha-hang-1.jpg',
    avt: 'https://galaxylands.com.vn/wp-content/uploads/2022/03/shark-hung-tap-doan-cen-group.jpg',
    name: 'Shark Hưng',
    date: '22/07/2022',
    time: '2 đêm. Tháng 6/2022',
    premiumTwin: 'Premium Twin',
    evaluate: 'Dịch vụ tốt, chăm sóc khách hàng tận tâm',
    coment: 'Bữa ăn sáng phong phú, phòng đẹp.Thiết kế phòng hiện đại, sáng tạo - Hệ thống nước mạnh dù mình ở tầng cao nhất - Có chiến dịch bảo vệ môi trường - Dọn phòng nhanh chóng - Wifi ổn định, tivi nhiều kênh và rõ nét - Có hầm đỗ xe tiện nghi - Có hồ bơi và quầy bar - Check out nhanh chóng - Toàn bộ nhân viên đều rất trẻ',
    point: '9.6',
    cmt: 'Tuyệt vời',
  },
  {
    id: 4,
    imgE: 'https://www.hoteljob.vn/files/Ni%20-%20%E1%BA%A2nh%20HTJ/2018/Th%C3%A1ng%206/BS%20t6/Tieu-chuan-dich-vu-khach-san-5-sao-01.jpg',
    avt: 'https://bstyle.vn/wp-content/uploads/2019/04/shark-nguyen-thanh-viet-1.jpg',
    name: 'Shark Việt',
    date: '15/06/2022',
    premiumTwin: 'Premium Twin',
    time: '2 đêm. Tháng 6/2022',
    evaluate: 'Đồ ăn ngon, có các trò chơi giải trí thú vị',
    coment: 'Bữa ăn sáng phong phú, phòng đẹp.Thiết kế phòng hiện đại, sáng tạo - Hệ thống nước mạnh dù mình ở tầng cao nhất - Có chiến dịch bảo vệ môi trường - Dọn phòng nhanh chóng - Wifi ổn định, tivi nhiều kênh và rõ nét - Có hầm đỗ xe tiện nghi - Có hồ bơi và quầy bar - Check out nhanh chóng - Toàn bộ nhân viên đều rất trẻ',
    point: '9.8',
    cmt: 'Tuyệt vời',
  },
  {
    id: 5,
    imgE: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxc6Y5OcGv0aA2S-HBAgHNY_p-lxPSFY05VQ&usqp=CAU',
    avt: 'https://cafefcdn.com/thumb_w/650/203337114487263232/2021/7/23/photo1627030924824-16270309250651512805054.jpg',
    name: 'Shark Liên',
    date: '15/06/2022',
    premiumTwin: 'Premium Twin',
    time: '2 đêm. Tháng 6/2022',
    evaluate: 'Khách sạn xanh, sạch đẹp, thân thiện với khách hàng',
    coment: 'Bữa ăn sáng phong phú, phòng đẹp.Thiết kế phòng hiện đại, sáng tạo - Hệ thống nước mạnh dù mình ở tầng cao nhất - Có chiến dịch bảo vệ môi trường - Dọn phòng nhanh chóng - Wifi ổn định, tivi nhiều kênh và rõ nét - Có hầm đỗ xe tiện nghi - Có hồ bơi và quầy bar - Check out nhanh chóng - Toàn bộ nhân viên đều rất trẻ',
    point: '9.8',
    cmt: 'Tuyệt vời',
  },
]